apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-v2
spec:
  replicas: {{ .Values.frontend2.replicaCount }}
  selector:
    matchLabels:
      app: frontend
      version: v2
  template:
    metadata:
      labels:
        app: frontend
        version: v2
      # annotations:
      #   traffic.sidecar.istio.io/includeInboundPorts: ""
      #   traffic.sidecar.istio.io/excludeInboundPorts: "80,443"
      #   traffic.sidecar.istio.io/excludeOutboundIPRanges: "substitute_for_correct_subnet_range"
      #   sidecar.istio.io/inject: 'true'
    spec:
      serviceAccountName: frontend-sa
      containers:
      - name: frontend
        image: "{{ .Values.frontend2.image.repository }}:{{ .Values.frontend2.image.tag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.frontend2.service.port }}
        #added to test HPA
        resources:
          requests:
            cpu: "100m" # Minimum CPU
          limits:
            cpu: "200m" # Maximum CPU
