apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.service.name }}
spec:
  protocol: TCP
  ports:
    - port: {{ .Values.backend.service.port }}
  selector:
    app: {{ .Values.backend.service.name }}
  type: ClusterIP
