apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.service.name }}
spec:
  protocol: HTTP
  ports:
    - port: {{ .Values.frontend.service.port }}
  selector:
    app: {{ .Values.frontend.service.name }}
